# Generated by Django 3.2.1 on 2021-05-05 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dp', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.TimeField(choices=[('M', '09:00:00'), ('AN', '12:00:00'), ('E', '18:00:00')])),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advisor_network_app.advisor')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advisor_network_app.user')),
            ],
        ),
    ]
