# Generated by Django 3.2.1 on 2021-05-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_network_app', '0002_alter_advisor_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='dp',
            field=models.ImageField(upload_to='profpic'),
        ),
    ]
