# Generated by Django 3.2.1 on 2021-05-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_network_app', '0007_alter_advisor_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='dp',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
