# Generated by Django 3.2.1 on 2021-05-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_network_app', '0010_alter_advisor_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='designation',
            field=models.CharField(default='Advisor', max_length=50),
        ),
    ]
