# Generated by Django 3.2.1 on 2021-05-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_network_app', '0011_advisor_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='designation',
        ),
    ]
