# Generated by Django 3.2.1 on 2021-05-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_network_app', '0012_remove_advisor_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='timing',
        ),
        migrations.AddField(
            model_name='booking',
            name='bktime',
            field=models.DateTimeField(null=True),
        ),
    ]
