# Generated by Django 3.2.1 on 2021-05-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_network_app', '0013_auto_20210520_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='aid',
            new_name='a_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='uid',
            new_name='u_id',
        ),
    ]
