# Generated by Django 3.2.1 on 2021-05-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_network_app', '0015_auto_20210521_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='a_id',
            new_name='advisor',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='u_id',
            new_name='user',
        ),
    ]
