# Generated by Django 3.2.1 on 2021-05-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_network_app', '0016_auto_20210521_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='dp',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
    ]
